# 빌드 설정
[build]
  command = "CI= npm run build"
  functions = "netlify/functions/"
  publish = "public"

# 개발 모드 설정
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public"
  autoLaunch = true

# Netlify Functions 설정
[functions]
  node_bundler = "esbuild"

# 리디렉트 설정 (API 요청만 함수로 전달)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
